# Generated by Django 3.0.3 on 2020-04-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecored',
            new_name='AccessRecord',
        ),
    ]
